# Generated by Django 5.0.2 on 2024-03-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankUser',
            new_name='BankAccount',
        ),
    ]
