# Generated by Django 5.0.2 on 2024-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_bankuser_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
