# Generated by Django 5.0.2 on 2024-03-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bankaccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='username',
            field=models.CharField(default='abc', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
